Repository LuizaMaluf/req_Canva_2024.1, pull requests merged in 2024-07, with the labels that each got.

#5 Docs/richpicture
  docs/images/rich_picture_geral_00.jpg
  docs/images/rich_picture_usuario_00.jpg
  docs/rich_picture.md
Labels: Rich Picture

#6 Reunião 1
  docs/index.md
  docs/reuniao1.md
  docs/rich_picture.md
  mkdocs.yml
Labels: Reunião

#7 Introdução da argumentação
  docs/argumentacao.md
  mkdocs.yml
Labels: documentation

#8 Documentação da primeira argumentação
  docs/argumentacao.md
  docs/images/argumentacao_1.jpg
Labels: documentation

#20 [feature request] Add mind map as a brainstorming artefact
  docs/elicitacao/brainstorming.md
  docs/images/Mapa-Mental.png
  pyproject.toml
Labels: documentation

#21 Adiciona video Primeira Entrega
  docs/entregas/entrega1.md
  mkdocs.yml
Labels: documentation
